DATASET:
  NAME: tweets
  SENT_LEN: 30
TRAIN:
  BATCH_SIZE: 256
  NUM_EPOCHS: 25
  NUM_WORKERS: 8
NET:
  NUM_CLASSES: 3
  MODEL: "sentiformer"
  LR: 0.0001
  OPT: "SGD"
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
